version: "3"

services:
  tor:
    build:
      context: ./tor
      dockerfile: Dockerfile
    links:
      - proxy
    volumes:
      - LOCAL_SECRETS_PATH:/tor
  proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    expose: NGINX_PORTS
    links:
      - BACKEND_APP
  BACKEND_APP:
    image: BACKEND_IMAGE
    expose:
      - "BACKEND_PORT"
