version: "3"

services:
  tor:
    build:
      context: ./tor
      dockerfile: Dockerfile
    links:
      - proxy
    volumes:
      - LOCAL_SECRETS_PATH:/tor
  proxy:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    expose:
      - "10080"
      - "10081"
    links:
      - BACKEND_APP
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  BACKEND_APP:
    image: BACKEND_IMAGE
    expose:
      - "BACKEND_PORT"
